### ISSUE TITLE
RabbitMQ backend Book data Missing 'feed' and 'pair' ?

### ISSUE THREAD

**Issue by zhenpingfeng** [bmoscon/cryptofeed#192]
> python  demo_rabbitmq.py
 [*] Waiting for messages. To exit press CTRL+C
 [x] Received 'book {"timestamp": 1578128992.819561, "delta": false, "bid": {"7336.3": 0.28, "7333.9": 0.03936515}, "ask": {"7336.4": 4.870119, "7336.5": 0.04}}'
 [x] Received 'book {"timestamp": 1578128993.3211892, "delta": false, "bid": {"133.3": 1.462, "133.29": 0.131}, "ask": {"133.32": 2.58, "133.33": 2.43}}'
 [x] Received 'trades {"feed": "KRAKEN", "pair": "BTC-USD", "timestamp": 1578128993.036496, "side": "buy", "amount": 0.01514394, "price": 7336.4}'
 [x] Received 'book {"timestamp": 1578128993.4042351, "delta": false, "bid": {"7336.3": 0.28, "7333.9": 0.03936515}, "ask": {"7336.4": 4.85497506, "7336.5": `0.04}}'

cryptofeed version: master branch

**Comment by zhenpingfeng** [comment]
https://github.com/bmoscon/cryptofeed/pull/193
I submitted a pull request

**Comment by bmoscon** [comment]
@zhenpingfeng I see what you're saying now. It's definitely not something I want to add to the data for all backends, because book data is very high volume and thats a lot of repetition in the data, but most other backends get the data some other way (i.e. for redis its part of the key to the data). I'm conflicted on this because it does seem like something we'd need to add, so let me investigate a little and do some testing, but I think you're original PR will be what we want

**Comment by bmoscon** [comment]
The two things I want to look into are:
* is there some other reasonable way to convey this data (i.e. make it part of the q name)
* what affect will adding this have to cryptostore (i.e. how many changes, if any, will need to be made to that code base).

**Comment by bmoscon** [comment]
@zhenpingfeng i added the data to the messages, so should be all set now
