### ISSUE TITLE
Huge latency on trade data

### ISSUE THREAD

**Issue by rbdm-qnt** [bmoscon/cryptofeed#260]
I'm getting BitMEX trade and OB data, and I have a few questions about latencies:

1) When getting trade data I usually have about 0.3ms latency between timestamp and receipt_timestamp, and that's ok. However, if I measure the latency from the receipt timestamp to now using time() I always get latencies between 200 and 1200ms. My ping to BitMEX is 28ms. If I measure the same thing on OB data, the receipt_timestamp is always the same as the timestamp, and the latency from receipt timestamp to now is slightly above 28ms, which is correct. Why is that?

2) When I set the OB delta to true or false, is cryptofeed/store doing the OB reconstruction, or is it getting the already reconstructed OB directly from the exchange?  Edit: delta false adds about 25ms of latency, so I'm guessing cryptofeed does the reconstruction and that's how much it takes?

3) Being the timestamp and receipt timestamp the same in the OB, I have to assume one of the two is incorrect; is the receipt timestamp a duplicate, which would not be a problem, or is it the opposite, in which case there is a chance that OB data also has a 200-1200ms "hidden" latency like trade data?

**Comment by xiandong79** [comment]
For Q2.

IMO, from bitmex.py file, or in detail https://github.com/bmoscon/cryptofeed/blob/4b3ca1bc3a2ed4ffc89dce784d0d866d557696de/cryptofeed/exchange/bitmex.py#L117, we can know that no matter "set the OB delta to true or false", cryptofeed or bitmex.py would re-construct the orderbook.

Fundamentally, this is due to bitmex.py subscribes the  "BITMEX: 'orderBookL2'", according to https://github.com/bmoscon/cryptofeed/blob/4b3ca1bc3a2ed4ffc89dce784d0d866d557696de/cryptofeed/standards.py#L84

**Comment by bmoscon** [comment]
If you are using cryptostore, how are you getting the data delivered to your application?

**Comment by rbdm-qnt** [comment]
> If you are using cryptostore, how are you getting the data delivered to your application?

I'm using cryptostore with redis and zmq. 



> For Q2.
> 
> IMO, from bitmex.py file,
> 
> https://github.com/bmoscon/cryptofeed/blob/4b3ca1bc3a2ed4ffc89dce784d0d866d557696de/cryptofeed/exchange/bitmex.py#L117
> , we can know that no matter "set the OB delta to true or false", cryptofeed or bitmex.py would re-construct the orderbook.

Yes, I've tested the bitmex websocket and the exchange doesn't provide timestamps on OBs and doesn't provide already reconstructed OBs.

**Comment by bmoscon** [comment]
for 1 - if there is no exchange provided timestamp, receipt == timestamp. For any update if the receipt and timestamp are equivalent, you know there was no exchange provided timestamp

2. was answered. 

3. see 1. 


For your second set of points, I dont see any way to get what the "real" timestamp is. If the exchange doesn't provide it, not sure what can be done.

As far as latencies are concerned, there is going to be latency involved in writing data to redis and reading it back out. Without knowing what your specific setup is and what your config is, i couldnt hope to guess if what you are seeing is normal or not. 200-1200ms latencies do not seem crazy.

**Comment by bmoscon** [comment]
I added in some metrics for bitmex's book processing. Here are some results. Note for the first entry, the large max is from the initial book update (which is thousands deep per side):

For last 1000 executions:
   Min: 0.0019073486328125 ms
   Max: 49.30400848388672 ms
   Average: 0.07050687616521663 ms
For last 1000 executions:
   Min: 0.003814697265625 ms
   Max: 0.1609325408935547 ms
   Average: 0.023631068257304218 ms
For last 1000 executions:
   Min: 0.0026226043701171875 ms
   Max: 0.1621246337890625 ms
   Average: 0.015560563627656523 ms
For last 1000 executions:
   Min: 0.0019073486328125 ms
   Max: 0.11396408081054688 ms
   Average: 0.015208056637576291 ms
For last 1000 executions:
   Min: 0.00286102294921875 ms
   Max: 0.16999244689941406 ms
   Average: 0.01804502336652605 ms
For last 1000 executions:
   Min: 0.0030994415283203125 ms
   Max: 0.16617774963378906 ms
   Average: 0.01781899016815704 ms
For last 1000 executions:
   Min: 0.0026226043701171875 ms
   Max: 0.19502639770507812 ms
   Average: 0.01811647748613691 ms
For last 1000 executions:
   Min: 0.0019073486328125 ms
   Max: 0.09012222290039062 ms
   Average: 0.01331071158150931 ms


the averages are all pretty consistent around 0.012 ms -> 0.018 ms with maxes in the ~0.2 ms range. So, a far cry from the 200-1200 ms you're seeing. I'm going to continue adding in performance metrics, so I'll add redis next. Of course these will be my machine specific, but once the code is released you can run it on your end and see if you get different results.

**Comment by bmoscon** [comment]
@rbdm-qnt you all set with this?

**Comment by bmoscon** [comment]
This was the original content of this ticket:


1. When I get trade data from my own websocket, I get about 30ms latency from timestamp to now with 51ms ping to bitmex.com. This seems to work correctly. I don't know where the 1 second latency comes from when using cryptostore.
2. Still open.
3. Dived deeper into this, I've seen Mex does not provide a timestamp on OBs, but cryptofeed doesn't account for latency (IE: measuring latency from trade data and subtracting it from the OB receipt ts to calculate a more correct estimate of the real ts), which is an extremely important point, because it means that all the historical data collected by cryptostore is incorrect and can't be used for more HF backtesting, because trades timestamps don't match with the state of the OB at that given moment. This could be fairly easy to correct though!



and then later on:

```
If you are using cryptostore, how are you getting the data delivered to your application?
```
I'm using cryptostore with redis and zmq.

For Q2.
```
IMO, from bitmex.py file,
https://github.com/bmoscon/cryptofeed/blob/4b3ca1bc3a2ed4ffc89dce784d0d866d557696de/cryptofeed/exchange/bitmex.py#L117
, we can know that no matter "set the OB delta to true or false", cryptofeed or bitmex.py would re-construct the orderbook.
```
Yes, I've tested the bitmex websocket and the exchange doesn't provide timestamps on OBs and doesn't provide already reconstructed OBs.
