### ISSUE TITLE
Is the license a custom?

### ISSUE THREAD

**Issue by saleh-mir** [bmoscon/cryptofeed#314]
Hi. Thank you for the great package. This might be a silly question, but what is the type of license in the matter of the popular licenses like MIT, GPL, Apache, etc?

**Comment by bmoscon** [comment]
its the XFree86 license. 

It is here:

https://github.com/bmoscon/cryptofeed/blob/master/LICENSE

**Comment by olibre** [comment]
The body license is from the XFree86 License 1.1 (2004),
and the warranty notice is from the XFree86 License 1.0:
https://www.xfree86.org/legal/licenses.html

Note:
* The XFree86 License 1.0 is from the [MIT license](https://en.wikipedia.org/wiki/MIT_License).
* The XFree86 License 1.1 is not [OSI-approved](https://opensource.org/licenses/alphabetical) but [mentioned as GPL3-compatible](https://www.gnu.org/licenses/license-list.html#XFree861.1License) by the FSF.
* The main change is a new credit clause, similar to the one in the original [BSD license](https://en.wikipedia.org/wiki/BSD_license), but with a broader scope. 

Many projects relying on XFree86 found the new license unacceptable. Many of the XFree86 developers forked the XFree86 4.4 RC2 (last XFree86 source code based of the previous license version) and joined the X.Org Foundation due to disagreement with the new license and/or with the XFree86 management.

References:
* https://lwn.net/Articles/68841/
* https://en.wikipedia.org/wiki/XFree86#2004:_Licensing_controversy
* https://en.wikipedia.org/wiki/X.Org_Server#History

**Comment by saleh-mir** [comment]
@olibre thank you for your complete response. I highly appreciate the work that has gone through this code base. I personally think it would be better if the repository chose a more popular license for it to be less confusing. I already understand MIT, Apache, GPL, LGPL, etc I had never seen XFree86 which makes is hard for me whether to use it in my project or not.

**Comment by bmoscon** [comment]
@saleh-mir - nothing would prevent you from using this as a dependency in a project (i.e. just as a pypi dependency in setup.py or requirements.txt). If you want to take it and modify it to make your own library, or take parts and put into an application, the license needs to be included at the top of copied/modified files and credit needs to be given per clause number 3. So, its pretty open, even GNU says its GLP3 compliant.
