### ISSUE TITLE
How to Handle Custom Exception

### ISSUE THREAD

**Issue by Jay54520** [bmoscon/cryptofeed#408]
I want to handle my custom exception in callback but cryptofeed doesn't directly raise it  but trying to reconnect.

```
from cryptofeed import FeedHandler
from cryptofeed.callback import BookCallback
from cryptofeed.defines import L2_BOOK
from cryptofeed.exchanges import FTX


async def book(*args, **kwargs):
    raise ValueError


def main():
    f = FeedHandler()
    f.add_feed(FTX(pairs=['BTC-USD'], channels=[L2_BOOK], callbacks={L2_BOOK: BookCallback(book)}))
    f.run()


if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        # can't catch Exception
        print(e)
```

**Comment by bmoscon** [comment]
there is currently no way to handle an exception. cryptofeed handles them internally and resets the connection as needed. Is there a need to provide a custom exception handler?

**Comment by bmoscon** [comment]
@Jay54520 let me know if a user defined callback handler is something you'd want to see. I can see it being done one of three ways.

1. User specifies list of exceptions its DOES not want cryptofeed to handle
2. User provides list of exceptions and corresponding handlers for said exceptions
3. user provides only an exception handler that will be used to handle ALL exceptions, including all internal cryptofeed defined exceptions


Let me know if you want to see any of these. If I don't hear back from you I'll assume your question was answered and you're all set.

**Comment by Jay54520** [comment]
I prefer `1`. After cryptofeed raising the exception, user can catch and handle it in his existing exception handler, `2` is the same as `1` in this scene. The majority exceptions that user want to handle are in the callbacks of cryptofeed but not the internal logic such as connecting, parsing raw response, so user doesn't want to handle all exceptions in `3`.

**Comment by tristan-murfitt-elw** [comment]
@bmoscon can you confirm what happens if a feed connection (in `feedhandler._connect`) fails after all retries? It looks as though `ExhaustedRetries()` is raised and then this feed task just exists silently. A custom exception handler would be useful to detect if any Markets/Symbols are no longer actively running, so they can be handled in some way by the parent task (eg. send out an email notification).

1. Have you seen any solutions for monitoring **all** the feeds and ensuring no tasks are inactive?
2. Are there any other places in the library that we should be mindful of, or is it just the `feedhandler._connect` which may silently kill a feed? 

eg. if I'm having connection issues locally, such as SSL errors, (2) happens a lot. I can solve this by:
```py
    fh = FeedHandler(retries=1)

    def fh_connect_handler(func):
        @wraps(func)
        async def wrapped(*args, **kwargs):
            try:
                return await func(*args, **kwargs)
            except ExhaustedRetries as e:
                feed, exch = args[1].keywords['options'], args[2].__globals__['__name__']
                # send email to alert of failed feed
        return wrapped

    fh._connect = fh_connect_handler(fh._connect)
```

**Comment by bmoscon** [comment]
fixed in master. You have to provide a list of exception instances you want to handle, and provide an asyncio exception handler to actually handle them. See https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.set_exception_handler for specifics on that exception handler
