### ISSUE TITLE
BookDelta doesn't support custom callback

### ISSUE THREAD

**Issue by jamesmundy** [bmoscon/cryptofeed#49]
I've just begun experimenting with getting updates for a level 2 order book and I've noticed my custom callback for the `BOOK_DELTA` is not being called.

Looking through the code in the `feed.py` file I notice that the update callback is treated differently and not called unless it is an instance of `BookUpdateCallback`. 
https://github.com/bmoscon/cryptofeed/blob/3cc1f686134f497fc7ec7ea4405acf3691377d00/cryptofeed/feed.py#L44-L49

This means I can't supply my own custom callback in a similar way as to how you have created and used the [backend callbacks](https://github.com/bmoscon/cryptofeed/tree/20b366d029298bcf77a78448e6f210622e95674f/cryptofeed/backends), I can get around it but I was wondering if there was a reason for this? Perhaps something like this would be more flexible?

```self.callbacks = {TRADES: Callback(None),
                          TICKER: Callback(None),
                          L2_BOOK: Callback(None),
                          L3_BOOK: Callback(None),
                          VOLUME: Callback(None),
                          FUNDING: Callback(None),
			  BOOK_DELTA: Callback(None)}

        if callbacks:
            for cb in callbacks:
                self.callbacks[cb] = callbacks[cb]
                if (cb == BOOK_DELTA):
                    self.do_deltas = True```

**Comment by bmoscon** [comment]
You're making me realize I should spend more time on the docs :)

You can see an example of how the deltas work here: 

https://github.com/bmoscon/cryptofeed/blob/master/examples/demo_book_delta.py

You need two callbacks, the book callback (either L2 or L3) and the bookUpdateCallback. The normal book callback will be called with complete updates based on a configurable interval, the `book_interval` kwarg on the Feed class. It will also be called on reconnects and dropped/missed messages. The delta callback will be called all other times with the deltas. You can use custom callbacks, but you need to have handlers for both and handle both since the message signature for both types are completely different. 


Does that answer your question/concern?

**Comment by jamesmundy** [comment]
I think some more documentation could be useful but I was easily able to get started with the documentation that was there.
I found the book delta demo but, as I mentioned in my other question, I am saving updates to Postgres using a custom callback in a similar way as to how you have done for other storage types like Redis. Creating a postgres callback class for the Level 2 callback worked fine but the Book Delta callback was not being called because the class wasn't an instance of `BookUpdateCallback`. Once your change is released this won't be the case so my code will now work - thanks for that!

**Comment by bmoscon** [comment]
I did push my change to master. I'll get some more things in this week and release a new version to PyPi this weekend.

**Comment by bmoscon** [comment]
havent forgotten about this, just trying to get one or two more small fixes in before rolling a new release

**Comment by bmoscon** [comment]
new version released to pypi, closing
