### ISSUE TITLE
add support for sequence ID in full book and book delta

### ISSUE THREAD

**Issue by kyle-downey** [bmoscon/cryptofeed#537]
**Is your feature request related to a problem? Please describe.**
In order to synchronize a delta feed and a full book feed it is very useful to have a monotonically increasing sequence number associated with the underlying exchange book update; I know Coinbase Pro provides this on the feed, less sure about other exchanges. You can do this with timestamps but the integer is more robust.

**Describe the solution you'd like**
Optionally include a common sequence ID in both DELTA_BOOK and L2_BOOK callbacks.

**Describe alternatives you've considered**
This can be achieve by always subscribing to DELTA_BOOK and L2_BOOK as shown in one of the delta book demos, but synchronization is both more robust and, if the underlying exchange sequence is used, has other applications, e.g. gap detection and allowing you to overlay exchange REST order book snapshots with live ticking feeds to build books.

**Additional context**
N/A.

**Comment by bmoscon** [comment]
cryptofeed already tracks and accounts for sequence numbers, see https://github.com/bmoscon/cryptofeed/blob/master/docs/book_validation.md
if one is missing it will reset the book. Are you saying in addition to this you want to receive the sequence numbers in the callbacks?

**Comment by kyle-downey** [comment]
That's correct: I'd like to get the sequence numbers in the callbacks. The use case is network distribution: I want my feed handlers to publish deltas only to reduce the load, so book building will have to be done out of process.

**Comment by jinusean** [comment]
I can work on this as I need it as well. 
@bmoscon how do you propose we go about this? 

Possible options are:
1. A 'meta' dict parameter in the callback that other callbacks can use if necessary.
2. An 'update_id' parameter in the callback.
3. Adding an 'update_id' field in the 'book' object.

**Comment by bmoscon** [comment]
@jinusean so I haven't done the work yet, but this is my thought: 

Any time a new field is added to the main callback types (trades, book, etc) its a huge nightmare because all the backends code needs to be changed and tested. Because of this, I want to define data or slotted classes (I would need to spend some time profiling them vs dictionaries to determine the performance impact) for trades, books, etc. the callbacks would simply return these and the classes would define their own serialization methods that would be used for things like the backends. My plan was to make it an attribute of this new class for the book data. For the book data the impact would be nearly negligible or irrelevant since we're only creating a book object once per symbol per connection (the caveat being reconnects, etc). I dont want to do it only for book data though, so time needs to be spent to ensure that there is no performance impact using a data structure like this. If there is a better data structure that is similar and performant, I'm open to that too

**Comment by jinusean** [comment]
I don't have experience profiling slotted classes, but the faster attribute access should in theory also speed up the constant book updates. The additional typing support for class instances would also be a plus. Since I can't think of anything better I'll leave it up to you, but feel free to let me know if there's any way I can assist.

**Comment by bmoscon** [comment]
@jinusean - I did some profiling, the only real option is to use cython datatypes. I've started the work in the dtypes branch, it will be a week or two until its ready to be merged as nearly every file in the project will need to be updated

**Comment by bmoscon** [comment]
@kyle-downey once the branch is merged (see previous comment) then the sequence number will be exposed to you

**Comment by kyle-downey** [comment]
@bmoscon fantastic, thank you.

**Comment by tristan-murfitt-elw** [comment]
@bmoscon will this change allow us to enhance the TICK callbacks for exchanges that provide more info?

eg. Deribit tick feed comes with greeks, most other tick feeds come with "last price"

```python
    async def _ticker(self, msg: dict, timestamp: float):
        pair = self.exchange_symbol_to_std_symbol(msg['params']['data']['instrument_name'])
        ts = timestamp_normalize(self.id, msg['params']['data']['timestamp'])
        m = msg['params']['data']
        extra_fields = {
            'high': Decimal(m.get('max_price', 0)),
            'low': Decimal(m.get('min_price', 0)),
            'last': Decimal(m.get('last_price') or 0),   # nullable
            'mark_price': Decimal(m.get('mark_price', 0)),
            'underlying_price': Decimal(m.get('underlying_price', 0)),
            'volume': Decimal(m['stats'].get('volume') or 0),    # nullable
            'best_bid_size': Decimal(m.get('best_bid_amount', 0)),
            'best_ask_size': Decimal(m.get('best_ask_amount', 0)),
            'bid_iv': Decimal(m.get('bid_iv', 0)),
            'ask_iv': Decimal(m.get('ask_iv', 0)),
            'mark_iv': Decimal(m.get('mark_iv', 0)),
            **m.get('greeks', {}),  # vega, theta, rho, gamma, delta
        }
        await self.callback(TICKER, feed=self.id,
                            symbol=pair,
                            bid=Decimal(msg["params"]["data"]['best_bid_price']),
                            ask=Decimal(msg["params"]["data"]['best_ask_price']),
                            timestamp=ts,
                            receipt_timestamp=timestamp,
                            **extra_fields)
```

**Comment by bmoscon** [comment]
my plan would be to store the pre-defined/basic data + the raw message

**Comment by bmoscon** [comment]
this has been implemented and is currently in the master branch.
