### ISSUE TITLE
Arctic backend L2_BOOK support

### ISSUE THREAD

**Issue by zhenpingfeng** [bmoscon/cryptofeed#705]
Arctic backend missing L2_BOOK support.

**Comment by bmoscon** [comment]
this is intentional - arctic cant handle that volume of data unless you were to use a very specialized system, so I've left it out. If it were there people would use it and then raise issues complaining it didnt work or was too slow. I'll add a comment in this code that makes this clear. If you want to use arctic you need to batch the updates and do periodic writes. Arctic really only is good / makes sense for large quantities of data per write (i.e. if you were to write a days worth of data or more at once).
