### ISSUE TITLE
Strange bug related to Huobi, only the first trade.detail data can be received

### ISSUE THREAD

**Issue by rendonghai** [bmoscon/cryptofeed#74]
I encountered a very strange bug where the trade.detail could only receive a subscription success message ({'id': 'id10', 'status': 'ok', 'subbed': 'market.ethusdt.trade.detail', 'ts': 1554382490572}) and the first data message ({'ch': 'market.ethusdt.trade.detail', 'ts': 1554382096458, 'tick': {'id': 100807878420, 'ts': 1554382096446, 'data': [{'id': '10080787842028598565963', 'amount': Decimal('0.2'), 'price': Decimal('161.25'), 'direction': 'buy', 'ts': 1554382096446}]}}) after subscribing, and then only ping message ({'ping': 1554382491613}) after that.
Even stranger is the fact that the depth data subscription will receive subsequent messages as normal. I also tried Huobi's official demo https://github.com/huobiapi/Websocket-Python3-demo, and it worked perfectly.

**Comment by bmoscon** [comment]
@rendonghai I'll take a look

**Comment by bmoscon** [comment]
Ok, I'm not positive, but I'm pretty sure this is the issue:

Huobi has two exchanges, the global exchange and their US exchange. The current API is for the US based one, so it does have trade updates, but they are very infrequent (not much volume).

The demo you linked is for their global exchange / api, which has much more volume, and thus more updates. I'm pretty sure this is the case because the US exchange has data for USD denominated trades, whereas the global one does not. I can support both. I'll probably call one HuobiGlobal and the other Huobi, or Huobi and HuobiUS. Do you have a naming preference?

**Comment by rendonghai** [comment]
I finally found out that your Huobi exchange is linked. It seems that the trading volume of this exchange is so low that I think I have encountered a strange bug :). HuobiGlobal is the main website of Huobi, while other sub-websites include HuobiUS, HuobiKorea, etc. Except for the main website, the trading volume of other exchanges is pitifully low.
You can name sites like Huobi to HuobiGlobal, HuobiUS to HuobiUS, and so on.

**Comment by bmoscon** [comment]
fixed in latest release. Huobi is the global exchange, huobiUS is the USA exchange
