### ISSUE TITLE
max-values-per-tag limit exceeded

### ISSUE THREAD

**Issue by mansilla** [bmoscon/cryptofeed#94]
Hi, first of all. Thank you for the great job making this library.
Second. I'm receiving this error:

``` 
2019-05-15 19:05:35,334 : ERROR : Write to influxDB failed: 400 - {"error":"partial write: max-values-per-tag limit exceeded (100000/100000): measurement=\"BINANCE\" tag=\"id\" value=\"122289608\" dropped=1"}
```

I have fix it using the `influxdb.conf` setting described [here](https://docs.influxdata.com/influxdb/v1.5/administration/config/#max-values-per-tag-100000), but Im worried this may decrease the performance of the database since it seems to be a bad practice to have "too many tags".

Do you have some insights on this?

**Comment by bmoscon** [comment]
You can change the number of tags, they are used for indexing, so more tags, larger index. There are obviously performance implications here, it depends on your setup. I'm going to rework the influx callbacks so you can optionally:

1. Control what params are used for the tag
2. Optionally store data in separate timeseries (eg instead of all data for an exchange in a single measurement)

**Comment by mansilla** [comment]
Ok, some flexibility on the number and the content of tags would be great.
I don't think InfluxDB 2.0 will bring any alleviation to the data loss/overwrite issue. Since this is an immutable facts oriented database a timestamp/tags combination should be defining univocally a data registry, so I suppose this is exactly the expected behavior we should have for this use case.

**Comment by bmoscon** [comment]
should be fixed now. The tag is just the pair for the trades, so there should no longer be uniqueness issues on this front. Let me know if you still have issues.
